CREATE TABLE MESSAGES
(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    AUTHOR TEXT NOT NULL,
    CONTENT TEXT NOT NULL,
    DATE TEXT
);

INSERT INTO MESSAGES
    (AUTHOR, CONTENT, DATE)
VALUES
    ('Someone', 'Hello world', '21/11/19');

/*INSERT INTO MESSAGES
    (AUTHOR, CONTENT, DATE)
VALUES
    ('Someone', 'Hello world', '21/11/19');

INSERT INTO MESSAGES
    (AUTHOR, CONTENT, DATE)
VALUES
    ('Someone', 'Hello world', '21/11/19');

INSERT INTO MESSAGES
    (AUTHOR, CONTENT, DATE)
VALUES
    ('Someone', 'Hello world', '21/11/19');

INSERT INTO MESSAGES
    (AUTHOR, CONTENT, DATE)
VALUES
    ('Someone', 'Hello world', '21/11/19');*/
